# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "package.box"

  # > Vagrant is not able to mount VirtualBox shared folders on BSD-based
  # > guests. BSD-based guests do not support the VirtualBox filesystem at this
  # > time.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "setup",
    type: "shell",
    inline: <<-SHELL

      echo Installing Automation Voice
      sudo installer -pkg ./host/AutomationVoice.pkg -target /
  SHELL
end
